<?php 
$id = null;

if (isset($_GET["id"])) {
    $id=$_GET["id"];
    
    $query = $db->prepare('SELECT * FROM users WHERE id = :id');
    $query->bindParam(':id', $id, PDO::PARAM_INT);
    $query->execute();
    
    $user = $query->fetch(PDO::FETCH_ASSOC);
}
?>

<main class="container py-5 text-center">
    <h1>
        <?php
        if (isset($user["first_name"]) && isset($user["last_name"])) { 
            echo "{$user['first_name']} {$user['last_name']}";
        }
        ?>
    </h1>
    <h2>
        <?php 
        if (isset($user["email"])) 
        {
            echo $user["email"];
        }
        ?>
    </h2>
</main>